
name: 'libGDX iOS Release'
description: 'libGDX: Build Android app and upload to Google Play Store'
author: 'Simon Dalvai @dulvui'
branding:
  color: green
  icon: upload-cloud

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  service-account-json:
    description: 'Path to a valid Google service-account.json'
    required: false
    default: service-account.json
  package-name:
    description: 'Android package name'
    required: true
  keystore-path:
    description: 'Path to the keystore'
    required: false
    default: 'keystore.keystore'
  release-track:
    description: 'Release track: production, beta, alpha, internalsharing, internal'
    required: false
    default: 'internal'
  
runs:
  using: "composite"
  steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: list build-tools
      shell: bash
      run: ls -la /usr/local/lib/android/sdk/build-tools/latest/

    - name: Install zipalign, apksigner
      shell: bash
      run: sudo apt install zipalign apksigner

    - name: Build the libGDX application
      shell: bash
      run: ./gradlew android:assembleRelease

    - name: list android/build/outputs/apk/release
      shell: bash
      run: ls -la android/build/outputs/apk/release


    # - name: Align the unsigned APK
    #   shell: bash
    #   run: zipalign -v -p 4 android/build/outputs/apk/release/*.apk android/build/outputs/apk/release/unsigned-aligned.apk

    - name: Sign APK
      shell: bash
      run: apksigner sign --ks ${{ inputs.keystore-path }} --out android/build/outputs/apk/release/signed-aligned.apk android/build/outputs/apk/release/unsigned-aligned.apk

    - name: Publish to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ inputs.service-account-json }}
        packageName: ${{ inputs.package-name }}
        releaseFiles: android/build/outputs/apk/signed-aligned.apk
        track: ${{ inputs.release-track }}
        status: completed
