
name: 'libGDX Android upload'
description: 'libGDX: Build Android app and upload to Google Play Store'
author: 'Simon Dalvai @dulvui'
branding:
  color: green
  icon: upload-cloud

inputs:
  service-account-json:
    description: 'Path to a valid Google service-account.json'
    required: false
    default: service-account.json
  package-name:
    description: 'Android package name'
    required: true
  release-track:
    description: 'Release track: production, beta, alpha, internalsharing, internal'
    required: false
    default: 'internal'
  working-directory:
    required: false 
    default: .
  changes-not-sent-for-review:
    description: 'Indicates that the changes in this edit will not be reviewed until they are explicitly sent for review from the Google Play Console. Defaults to false'
    required: false 
    default: false
  
runs:
  using: "composite"
  steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build the libGDX application
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ./gradlew android:bundleRelease

    - name: Publish to Play Store
      uses: r0adkll/upload-google-play@v1.1.1
      with:
        serviceAccountJson: ${{ inputs.service-account-json }}
        packageName: ${{ inputs.package-name }}
        releaseFiles:  ${{ inputs.working-directory }}/android/build/outputs/bundle/release/*.aab
        track: ${{ inputs.release-track }}
        changesNotSentForReview: ${{ inputs.changes-not-sent-for-review }}
        status: completed